Dockerfile.openshift

/kind cleanup
**What this PR does / why we need it**:
Bumps the Dockerfile to use go 1.16 and OCP 4.8.

Bumps Dockerfile to OCP 4.8 and go 1.16

---

assets/csidriver.yaml
pkg/generated/bindata.go
pkg/operator/starter.go

Allows the operator to create the Azure Disk CSIDriver on the server.

Include CSIDriver creation in Operator

---

assets/csidriver.yaml
pkg/generated/bindata.go

The `csi.openshift.io/managed` annotation will be used to distinguish if a CSI driver is installed + managed by OCP (= the annotation is present) or by some 3rd party script / helm chart / operator.
Eventually, CSO should not start CSI driver operator when it sees CSIDriver without this annotation - it's a signal that the driver was installed by someone else.

Add "managed" annotation to CSIDriver

---

assets/node.yaml
pkg/generated/bindata.go

Add maxUnavailable to DaemonSet to speed up cluster upgrade by allowing more nodes to be updated simultaneously.

Bug 1947756: Add maxUnavailable to DaemonSet

---

assets/controller.yaml
pkg/generated/bindata.go

Use the same timeout values as upstream does.

Bug 1948555: Set timeouts according to upstream

---

assets/controller.yaml
assets/rbac/resizer_role.yaml
pkg/generated/bindata.go

This patch is the first iteration to fix the CSI certification failing tests.
- Fix resizer RBAC.
- Remove --extra-create-metadata=true from provisioner.

Bug 1948603: Fix some failing tests

---

test/e2e/manifest.yaml

Currently expansion e2e tests are failing due to an upstream issue:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/800
We'll re-enabled them once the issue is fixed.

Bug 1948603: Disable volume expansion e2e tests

---

test/e2e/manifest.yaml

This PR enables the volume expansion tests and disables online expansion, which is currently unsupported in Azure Disk.

Bug 1948603: Re-enable expansion e2e tests

---

assets/controller.yaml
assets/node.yaml
pkg/azurestackhub/azure_stack_hub_test.go
pkg/operator/starter.go

Use credentials provided by cloud-credential-operator (CCO, https://github.com/openshift/cluster-storage-operator/pull/206), i.e. Secret `azure-disk-credentials`. To use this secret, the operator adds an init container to driver pods to merge cloud.conf from the host (without the credentials) with the provided secret.  The init container uses cluster-cloud-controller-manager-operator's `azure-config-credentials-injector` that does the merge.
Therefore:
* Replace `${CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE}` with the right image name.
* Add `azure-config-credentials-injector` to the CSI driver pod as an init container.
* Make sure to restart all pods when the secret provided by CCO changes. This part should move to library-go eventually.

Bug 1992875: Use own cloud credentials

---

assets/csidriver.yaml
go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/modules.txt

Always apply fsGroup and don't depend on heuristics.
It's important when in-tree volume plugin provisions PVs with `fsType: ""` by default - when CSI migration is enabled, CSI volume plugin gets a volume with `fsType: ""` and it must decide the volume still needs fsGroup applied.
Bump library-go to get ApplyCSIDriver fixes to re-create CSIDriver when a change in needed.

Fix CSIDriver fsGroupPolicy

---

assets/controller.yaml

Sync arguments of all containers with the upstream deployment helm chart, https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/07a62580519e28d1bf9a7bd7adf11615d337cdbc/charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
I'd prefer to use the same parameters as upstream, for easy comparison between CSI driver versions.

Bug 2073373: Sync cmdline arguments with upstream

---

test/e2e/manifest.yaml

We have seen some flakes caused by Azure being slow to provision volumes.
This patch increases the pod startup timeout in e2e tests, which should reduce the number of flakes.

Bug 2062152: Increase pod startup timeout in e2e tests

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/config/serving/server.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/modules.txt

When the cluster-csi-snapshot-controller-operator is not deployed, (through the CSISnapshot capability) the VolumeSnapshotClass CRD is not created at all.
In that case, it doesn't make sense to deploy the CR, otherwise the operator gets degraded.

[release-4.12] OCPBUGS-3425: Only deploy VolumeSnapshotClass if CRD exists

---

assets/node.yaml

Currently the CSI driver doesn't collect any metrics on the Node. However, by the default the CSI driver exposes the `0.0.0.0:29605` port if none is specified. As a result, set a localhost port to avoid exposing the port to the network.

OCPBUGS-3659: Don't expose metrics port to whole network

---

assets/controller.yaml
assets/node.yaml

Managed identity authentication has precedence over username+password from azure-disk-credentials Secret. Force disable it when merging cloud.conf json.
See https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/223 for what the new cmdline option does (it forces `useManagedIdentityExtension: false` in cloud.conf).

OCPBUGS-6658: Disable managed identity authentication

---

assets/controller.yaml

This is syncing with the values [from upstream](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/v1.26.2/csi-azuredisk-controller.yam).
To test this out I created a StatefulSet with 120 replicas and then deleted it (including the volumes). Without this patch I could see that requests were being rate-limited in the client side. Both in the attacher
```
$ oc -n openshift-cluster-csi-drivers logs azure-disk-csi-driver-controller-64884fb954-5bkbk csi-attacher | rg client-side
I0217 18:07:26.394533       1 request.go:533] Waited for 82.41369ms due to client-side throttling, not priority and fairness, request: PATCH:https://172.30.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-0c1519f43602836c2c51d6ef37d3ff786d08862b5f6026fc0c17aa738d66d912
(...)
```
and in the …

OCPBUGS-7617: Adjust client-side QPS, burst and worker threads in provisioner and attacher sidecars

---

assets/controller.yaml

This is syncing with the values [from upstream](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/v1.26.2/csi-azuredisk-controller.yam).
To test this out I created a StatefulSet with 120 replicas and then deleted it (including the volumes). Without this patch I could see that requests were being rate-limited in the client side. Both in the attacher
```
$ oc -n openshift-cluster-csi-drivers logs azure-disk-csi-driver-controller-64884fb954-5bkbk csi-attacher | rg client-side
I0217 18:07:26.394533       1 request.go:533] Waited for 82.41369ms due to client-side throttling, not priority and fairness, request: PATCH:https://172.30.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-0c1519f43602836c2c51d6ef37d3ff786d08862b5f6026fc0c17aa738d66d912
(...)
```
and in the …

[release-4.10] OCPBUGS-8020: Adjust client-side QPS, burst and worker threads in provisioner and attacher sidecars

---

assets/controller.yaml
assets/node.yaml
pkg/azurestackhub/azure_stack_hub_test.go
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
vendor/modules.txt

Driver controller deployment should load workload identity values to injector env to enable workload identity authentication.
The following keys need to be flagged as optional because their presence now depends on authentication method used:
- azure_client_secret
- azure_tenant_id
- azure_federated_token_file
Depends on: https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/245

CCO-324: add support for workload identity

---

assets/controller.yaml
assets/node.yaml
pkg/azurestackhub/azure_stack_hub_test.go
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
vendor/modules.txt

CCO-324: Unrevert "CCO-324: add support for workload identity"

---

pkg/operator/starter.go

- Adding WithSecretHashAnnotationHook() for azure-disk-csi-driver-controller ensures that new annotation is published in azure-disk-csi-driver-controller deployment. This, in turn, leads to controller pods restart.

STOR-1433: Restart `azure-disk-csi-driver-controller` Pods if metrics-serving-cert changed

---

pkg/azurestackhub/azure_stack_hub.go
pkg/dependencymagnet/dependencymagnet.go

Run `make update-gofmt` with go 1.21 to prepare the repo to merge to csi-operator that insists on clean `make verify-gofmt`.

STOR-1696: Fix gofmt

---

README.md

Add a warning to README that the repo is not used in 4.16.

STOR-1713: Mark the repository obsolete
